from wfc.types_ import Cell, Tile

unicode_tiles: Cell.SuperPosition = (
    Tile(" ", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("═", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("║", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("╔", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("╚", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("╗", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("╝", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
    Tile("╠", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("╣", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("╦", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("╩", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("╬", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
)

circuit_tiles: Cell.SuperPosition = (
    Tile("img/tiles/circuit/circuit_0_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/circuit/circuit_0_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/circuit/circuit_0_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/circuit/circuit_0_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/circuit/circuit_32_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/circuit/circuit_32_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/circuit/circuit_32_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/circuit/circuit_32_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/circuit/circuit_64_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/circuit/circuit_64_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/circuit/circuit_64_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/circuit/circuit_64_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/circuit/circuit_96_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/circuit/circuit_96_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/circuit/circuit_96_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/circuit/circuit_96_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
)

molecule_tiles: Cell.SuperPosition = (
    Tile("img/tiles/molecule/molecule_0_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/molecule/molecule_0_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/molecule/molecule_0_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/molecule/molecule_0_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/molecule/molecule_32_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/molecule/molecule_32_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/molecule/molecule_32_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/molecule/molecule_32_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/molecule/molecule_64_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/molecule/molecule_64_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/molecule/molecule_64_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/molecule/molecule_64_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/molecule/molecule_96_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/molecule/molecule_96_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/molecule/molecule_96_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/molecule/molecule_96_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
)

brickwall_tiles: Cell.SuperPosition = (
    Tile("img/tiles/brickwall/brickwall_0_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/brickwall/brickwall_0_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/brickwall/brickwall_0_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/brickwall/brickwall_0_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/brickwall/brickwall_32_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/brickwall/brickwall_32_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/brickwall/brickwall_32_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/brickwall/brickwall_32_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/brickwall/brickwall_64_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/brickwall/brickwall_64_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/brickwall/brickwall_64_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/brickwall/brickwall_64_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/brickwall/brickwall_96_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/brickwall/brickwall_96_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/brickwall/brickwall_96_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/brickwall/brickwall_96_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
)

border_tiles: Cell.SuperPosition = (
    Tile("img/tiles/border/border_0_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/border/border_0_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/border/border_0_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/border/border_0_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/border/border_32_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/border/border_32_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/border/border_32_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/border/border_32_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/border/border_64_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/border/border_64_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/border/border_64_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/border/border_64_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/border/border_96_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/border/border_96_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/border/border_96_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/border/border_96_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
)

celtic_tiles: Cell.SuperPosition = (
    Tile("img/tiles/celtic/celtic_0_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/celtic/celtic_0_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/celtic/celtic_0_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/celtic/celtic_0_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/celtic/celtic_32_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/celtic/celtic_32_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(0))),
    Tile("img/tiles/celtic/celtic_32_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/celtic/celtic_32_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(1), Tile.Socket(1))),
    Tile("img/tiles/celtic/celtic_64_0.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/celtic/celtic_64_32.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/celtic/celtic_64_64.png", (Tile.Socket(1), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/celtic/celtic_64_96.png", (Tile.Socket(1), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/celtic/celtic_96_0.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/celtic/celtic_96_32.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(0))),
    Tile("img/tiles/celtic/celtic_96_64.png", (Tile.Socket(0), Tile.Socket(1), Tile.Socket(0), Tile.Socket(1))),
    Tile("img/tiles/celtic/celtic_96_96.png", (Tile.Socket(0), Tile.Socket(0), Tile.Socket(0), Tile.Socket(1))),
)
